source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'SDKSampleApp' do
    pod 'Alamofire', '~> 4.0'
end

target 'SDKSampleAppTests' do

end

target 'SDKSampleAppUITests' do

end

