source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'SDKSampleApp' do
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
    pod 'RealmSwift'
end

target 'SDKSampleAppTests' do
    pod 'RealmSwift'
    pod 'Quick'
    pod 'Nimble'
end

target 'SDKSampleAppUITests' do
    pod 'RealmSwift'
    pod 'Quick'
    pod 'Nimble'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
